# Change these first
owner: GeoportalIGM-ec # Your GitHub organization or username, where this repository lives
repo:  NTRIP-monitor # The name of this repository

sites:
#  - name: Geoportal IGM
#    url: https://www.geoportaligm.gob.ec
  - name: CASTER NTRIP IGM (Principal)
    url: http://regme-ip.igm.gob.ec:2101
  - name: CASTER NTRIP IGM-ESPOCH (Backup)
    url: http://regme-ip.espoch.edu.ec:2101

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /NTRIP-monitor
  logoUrl: https://raw.githubusercontent.com/GeoportalIGM-ec/NTRIP-monitor/master/assets/igm-icon.svg
  name: Monitoreo NTRIP IGM Ecuador
  theme: light
  
  
  introTitle: "**Geoportal IGM** monitoreo en tiempo real de los servicios CASTER de NTRIP del IGM Ecuador"
  introMessage: [Geoportal IGM](https://www.geoportaligm.gob.ec).
  
  navbar:
    - title: Estado
      href: /NTRIP-monitor
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO
  
  i18n:
    activeIncidents: Incidentes activos
    allSystemsOperational: Todos los sistemas están operativos

# Upptime also supports notifications, assigning issues, and more
# Mirar https://upptime.js.org/docs/configuration

# WorkflowSchedule por default
#workflowSchedule:
#  graphs: "0 0 * * *"
#  responseTime: "0 23 * * *"
#  staticSite: "0 1 * * *"
#  summary: "0 0 * * *"
#  updateTemplate: "0 0 * * *"
#  updates: "0 3 * * *"
#  uptime: "*/5 * * * *"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 */1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
